### ISSUE TITLE
What is the suggested: a) generator and b) node traversal library for Syntax Tree ASTs

### ISSUE THREAD

**Issue by aaronlippold** [ruby-syntax-tree/node-syntax-tree#49]
Hello, first very cool work!

For a)

Assuming I parse and generate the AST and then 'do my processing and update the AST' which generator should I pass the modified AST to rewrite my transformed ruby file

for b) I was trying to do something simple like move a node in the tree and write out a new file, the docs don't seem to call out a specific library for OO style ast traversal, manipulation, unless the assumption is that we would use TreeWriter. Can you provide some insight or pointers to documentation or blog that might help?

**Comment by kddnewton** [comment]
We're deprecating this in favor of using the WASM bindings to https://github.com/ruby/prism.
